services:
  - type: static_site
    name: globaltrade360-frontend
    buildCommand: ""
    publishDir: "."
    routes:
      - src: /
        dest: /index.html
      - src: /admin-login
        dest: /admin-login.html
      - src: /admin-panel
        dest: /admin-panel.html
      - src: /dashboard
        dest: /dashboard.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
